apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  containers:
    - name: nginx-pod
      image: nginx
      ports:
        - containerPort: 80
      resources:
        requests:
          cpu: "120Mi"
          memory: "150M"
        limits:
          cpu: "150Mi"
          memory: "200M"
